# Generated by Claude
-- Disable foreign key checks during insert
SET FOREIGN_KEY_CHECKS = 0;

-- -------------------------------------------------------
-- USERS (18 total)
-- -------------------------------------------------------
INSERT INTO `user` (`username`, `city`, `state`, `email`, `cognito_id`) VALUES
#                                                                                   (1,  'user1',  'Madison',       'WI', 'user1@email.com',  '12345'),
#                                                                                   (2,  'user2',  'Milwaukee',     'WI', 'user2@email.com',  '23456'),
#                                                                                   (3,  'user3',  'Chicago',       'IL', 'user3@email.com',  '34567'),
                                                                                  ('user4',  'Indianapolis',  'IN', 'user4@email.com',  '45678'),
                                                                                  ('user5',  'Minneapolis',   'MN', 'user5@email.com',  '56789'),
                                                                                  ('user6',  'Columbus',      'OH', 'user6@email.com',  '67890'),
                                                                                  ('user7',  'Detroit',       'MI', 'user7@email.com',  '78901'),
                                                                                  ('user8',  'Kansas City',   'MO', 'user8@email.com',  '89012'),
                                                                                  ('user9',  'Nashville',     'TN', 'user9@email.com',  '90123'),
                                                                                  ('user10', 'Denver',        'CO', 'user10@email.com', '01234'),
                                                                                  ('user11', 'Portland',      'OR', 'user11@email.com', '11234'),
                                                                                  ('user12', 'Seattle',       'WA', 'user12@email.com', '22345'),
                                                                                  ('user13', 'Austin',        'TX', 'user13@email.com', '33456'),
                                                                                  ('user14', 'Atlanta',       'GA', 'user14@email.com', '44567'),
                                                                                  ('user15', 'Boston',        'MA', 'user15@email.com', '55678'),
                                                                                  ('user16', 'Phoenix',       'AZ', 'user16@email.com', '66789'),
                                                                                  ('user17', 'Charlotte',     'NC', 'user17@email.com', '77890'),
                                                                                  ('user18', 'Miami',         'FL', 'user18@email.com', '88901');

-- -------------------------------------------------------
-- VENUES (18 total)
-- -------------------------------------------------------
INSERT INTO `venue` (`user_id`, `name`, `city`, `state`, `description`, `street_address`) VALUES
                                                                                                    (1,  'The Iron Horse',        'Madison',       'WI', 'A beloved Madison institution hosting local and national acts since 1987. The Iron Horse boasts a 500-person standing room floor, a wraparound balcony.',                                  '123 Fake St'),
                                                                                                    (2,  'The Rave',              'Milwaukee',     'WI', 'One of Milwaukee''s oldest and most storied concert halls, The Rave offers three stages under one roof — from an intimate bar stage to a 2,500-capacity ballroom dripping in Victorian grandeur.',                                    '234 Fictitious Avenue'),
                                                                                                    (3,  'Metro Chicago',         'Chicago',       'IL', 'A legendary Wrigleyville venue that has hosted everyone from up-and-coming indie bands to iconic rock legends. Metro Chicago''s second-floor balcony offers unbeatable sightlines.',                                                  '345 Imaginary Place'),
                                                                                                    (4,  'The Rusty Nail',        'Indianapolis',  'IN', 'A gritty, intimate rock club known for loud guitars and cold beer. The Rusty Nail has launched countless local acts onto the national stage.',                                                                                        '456 Pretend Blvd'),
                                                                                                    (5,  'Northstar Amphitheater','Minneapolis',   'MN', 'An open-air amphitheater nestled along the riverbank, hosting everything from folk festivals to massive EDM nights under the stars.',                                                                                                 '567 Nonexistent Road'),
                                                                                                    (6,  'The Velvet Underground','Columbus',      'OH', 'A dimly lit, velvet-curtained club that specializes in indie and alternative acts. Known for its killer sound system and cozy 300-person capacity.',                                                                                  '678 Phantom Lane'),
                                                                                                    (7,  'Motor City Soundhouse', 'Detroit',       'MI', 'A storied venue in the heart of Detroit celebrating the city''s legendary music heritage, featuring nightly live acts across jazz, soul, and rock.',                                                                                  '789 Illusory Ave'),
                                                                                                    (8,  'The Blue Room',         'Kansas City',   'MO', 'A legendary jazz and blues room with warm lighting, exposed brick walls, and some of the best acoustic engineering in the Midwest.',                                                                                                  '890 Invented Street'),
                                                                                                    (9,  'Grand Ole Stage',       'Nashville',     'TN', 'A world-class country and Americana venue in the heart of Music City, with a wraparound balcony and a history stretching back over five decades.',                                                                                    '901 Fabricated Dr'),
                                                                                                    (10, 'Red Rocks West',        'Denver',        'CO', 'Inspired by Colorado''s iconic outdoor spirit, this venue blends natural stone aesthetics with state-of-the-art acoustics for an unforgettable live experience.',                                                                     '102 Fictional Ct'),
                                                                                                    (11, 'The Evergreen Room',    'Portland',      'OR', 'Portland''s premier indie and folk haven, housed in a converted warehouse draped in hanging plants and warm Edison bulb lighting.',                                                                                                   '113 Bogus Blvd'),
                                                                                                    (12, 'Rainier Live',          'Seattle',       'WA', 'A mid-sized concert hall celebrating Seattle''s rich music scene, from grunge legends to cutting-edge electronic artists playing beneath a stunning LED canopy.',                                                                     '224 Faux Place'),
                                                                                                    (13, 'Sixth Street Social',   'Austin',        'TX', 'Right in the heart of Austin''s famous music strip, this high-energy venue hosts nightly shows spanning rock, country, blues, and everything in between.',                                                                            '335 Made-Up Way'),
                                                                                                    (14, 'The Peach Pit',         'Atlanta',       'GA', 'A Southern soul and R&B institution, known for its gospel brunch series, late-night funk jams, and a stage that has hosted some of the South''s finest talent.',                                                                     '446 Pretend Path'),
                                                                                                    (15, 'Harbor Lights Hall',    'Boston',        'MA', 'A beautifully restored 19th-century waterfront hall turned concert venue, offering stunning harbor views and world-class acoustics for up to 1,200 guests.',                                                                          '557 Imagined Row'),
                                                                                                    (16, 'Desert Sun Arena',      'Phoenix',       'AZ', 'A sprawling indoor arena built for the desert heat, featuring cutting-edge sound and lighting rigs and hosting some of the biggest touring acts in the country.',                                                                     '668 Fictitious Pkwy'),
                                                                                                    (17, 'The Carolina Room',     'Charlotte',     'NC', 'A beloved mid-sized venue championing Southern rock, bluegrass, and Americana with a laid-back vibe, excellent sightlines, and a top-shelf bourbon selection.',                                                                      '779 Simulated St'),
                                                                                                    (18, 'Tropicana Sound Club',  'Miami',         'FL', 'Miami''s hottest live music destination, blending Latin rhythms, reggaeton, and world music in a vibrant waterfront setting with an open-air dance floor.',                                                                          '880 Synthetic Ave');

-- -------------------------------------------------------
-- PERFORMERS (18 total)
-- -------------------------------------------------------
INSERT INTO `performer` (`name`, `description`, `genre`, `user_id`) VALUES
                                                                              ('The River Bends',       'A Madison-based rock band known for their anthemic choruses and introspective lyrics. The River Bends have been a cornerstone of the Wisconsin music scene for over a decade, selling out The Iron Horse every time they take the stage.',                            'Rock',       1),
                                                                              ('Neon Prairie',          'Milwaukee''s premier pop act, blending infectious hooks with lush synth arrangements. Neon Prairie''s energetic live show has earned them fans across the Midwest and a reputation as one of the most exciting acts to emerge from the Great Lakes region.',         'Pop',        2),
                                                                              ('The Starling Few',      'A Chicago indie band crafting delicate, layered soundscapes from acoustic guitars, vintage keys, and three-part harmonies. Their intimate live performances have made them a staple of the Chicago and broader Midwest indie circuit.',                               'Indie',      3),
                                                                              ('The Midnight Clause',   'A brooding jazz quartet from Indianapolis known for their late-night improvisational sets and cinematic soundscapes that blur the line between jazz and film score.',                                                                                                 'Jazz',       4),
                                                                              ('Dusty Horizon',         'A country outfit from Minnesota that blends heartland storytelling with lush pedal steel arrangements, earning a devoted following across the Great Plains.',                                                                                                         'Country',    5),
                                                                              ('Crown the Empire',      'Columbus-born hip-hop collective bringing razor-sharp lyricism and hard-hitting production to stages across the Midwest and beyond.',                                                                                                                                'Hip-Hop',    6),
                                                                              ('Velvet Static',         'A Detroit-bred R&B duo whose silky harmonies and live band arrangements draw equally from Motown''s golden era and contemporary neo-soul.',                                                                                                                          'R&B',        7),
                                                                              ('Circuit Breaker',       'Kansas City''s most electrifying electronic act, building massive walls of synthesized sound and pulsating rhythms that keep dancefloors moving until dawn.',                                                                                                        'Electronic', 8),
                                                                              ('The Nashville String Co.','A Nashville-based classical crossover ensemble that reimagines orchestral masterworks alongside original compositions, performing in venues from intimate halls to open-air festivals.',                                                                            'Classical',  9),
                                                                              ('Iron Parish',           'A thunderous metal outfit from Denver whose crushing riffs and operatic vocals have earned them a reputation as one of the hardest-working bands on the Rocky Mountain circuit.',                                                                                    'Metal',      10),
                                                                              ('Fern & the Foxes',      'A Portland folk collective weaving intricate acoustic guitar work, layered harmonies, and nature-inspired lyrics into sets that feel like a walk through an old-growth forest.',                                                                                     'Folk',       11),
                                                                              ('Mudwater Revival',      'A Seattle blues band steeped in the tradition of the Delta masters, bringing raw slide guitar, soulful vocals, and a genuine reverence for the roots of American music.',                                                                                            'Blues',      12),
                                                                              ('Kingfish Roots',        'An Austin-based reggae band channeling the spirit of Kingston through a Texas lens, mixing sun-soaked grooves with politically charged lyrics and irresistible riddims.',                                                                                            'Reggae',     13),
                                                                              ('Georgia Gold',          'An Atlanta soul powerhouse fronted by a three-octave soprano, backed by a full horn section and rhythm unit that brings the heat of Southern soul to every performance.',                                                                                            'Soul',       14),
                                                                              ('Static Revolt',         'Boston''s loudest punk export, known for blistering 40-minute sets, politically charged anthems, and a fiercely loyal fanbase that packs every venue from the floor to the rafters.',                                                                               'Punk',       15),
                                                                              ('Los Fuegos',            'A Phoenix-based Latin fusion band combining flamenco, cumbia, and salsa with modern pop production for a sound that is as danceable as it is culturally rich.',                                                                                                     'Latin',      16),
                                                                              ('The Revival Choir',     'A Charlotte gospel ensemble that transforms concert stages into full worship experiences, featuring soaring vocal arrangements, live drums, and an energy that leaves audiences breathless.',                                                                         'Gospel',     17),
                                                                              ('Sunken Groove',         'Miami''s premier funk band, delivering non-stop bass-driven grooves, tight brass stabs, and showmanship that turns every performance into an all-out dance party.',                                                                                                  'Funk',       18);

-- -------------------------------------------------------
-- EVENTS (23 total)
-- -------------------------------------------------------
INSERT INTO `event` (`event_start`, `title`, `venue_id`, `description`, `ticket_price`) VALUES
                                                                                                                ('2026-05-01 17:55:23', 'The River Bends: Homecoming Night',         1,  'The River Bends return to their hometown stage at The Iron Horse for a special homecoming celebration. Expect a career-spanning set, surprise guests from the Madison music community, and an emotional night for band and fans alike.',                                                       10.50),
                                                                                                                ('2026-05-02 15:56:23', 'Neon Prairie: Lights Up Tour',              2,  'Neon Prairie brings their dazzling Lights Up Tour to The Rave, featuring the full live band, a stunning LED production, and every hit from their acclaimed debut record. This is the pop show Milwaukee has been waiting for.',                                                              20.00),
                                                                                                                ('2026-05-03 11:56:23', 'The Starling Few: Acoustic Sessions',       3,  'Metro Chicago hosts The Starling Few for a rare all-acoustic performance. No amplifiers, no frills — just three voices, a handful of instruments, and the songs that made Chicago fall in love with this band. A truly special free evening.',                                                NULL),
                                                                                                                ('2026-06-01 18:00:00', 'After Midnight: An Evening of Jazz',        4,  'The Midnight Clause returns to The Rusty Nail for a special extended set celebrating the release of their debut album. Expect deep improvisations, surprise guest soloists, and an atmosphere as warm as a late-night whiskey.',                                                             15.00),
                                                                                                                ('2026-06-05 19:00:00', 'Wide Open Spaces Tour',                     5,  'Dusty Horizon brings their celebrated Wide Open Spaces Tour to the Northstar Amphitheater, performing fan favorites and brand-new material under the open Minnesota sky. Doors open at 6 PM for a full evening of heartland country.',                                                        NULL),
                                                                                                                ('2026-06-10 20:00:00', 'Crown the Empire: Live & Unfiltered',       6,  'Crown the Empire takes over The Velvet Underground for a raw, unfiltered live performance showcasing their latest mixtape alongside classic cuts. This intimate show is strictly limited to 300 fans.',                                                                                       22.00),
                                                                                                                ('2026-06-12 17:30:00', 'Velvet Static: Soul Session Vol. 1',        7,  'Motor City Soundhouse hosts an intimate soul session with Velvet Static, a night dedicated to the deep grooves and soaring harmonies of Detroit''s finest R&B duo. Dinner service available from 5:30 PM.',                                                                                  18.50),
                                                                                                                ('2026-06-15 21:00:00', 'Circuit Breaker: Surge Fest',               8,  'Circuit Breaker takes over The Blue Room for Surge Fest, a pulsating night of electronic music featuring three full hours of live synthesizer performance, lasers, and a sound system powerful enough to rattle your bones.',                                                                  NULL),
                                                                                                                ('2026-06-18 19:00:00', 'Strings & Things: A Classical Evening',    9,  'The Nashville String Co. graces the Grand Ole Stage for an extraordinary evening of classical crossover, featuring reimagined orchestral pieces alongside world premiere compositions. Smart casual attire encouraged.',                                                                        30.00),
                                                                                                                ('2026-06-20 18:30:00', 'Iron Parish: The Reckoning Tour',           10, 'Denver''s own Iron Parish brings The Reckoning Tour home to Red Rocks West for what promises to be the heaviest night in the venue''s history. Support from two regional metal acts. Earplugs provided at the door.',                                                                        12.00),
                                                                                                                ('2026-06-22 20:00:00', 'Fern & the Foxes: Into the Wild',           11, 'Fern & the Foxes debut their highly anticipated new record "Into the Wild" with a stunning live performance at The Evergreen Room, surrounded by a breathtaking installation of hanging foliage and candlelight.',                                                                            45.00),
                                                                                                                ('2026-06-25 17:00:00', 'Mudwater Revival: Blues on the Sound',     12, 'Rainier Live opens its doors for a free evening of authentic Delta blues as Mudwater Revival delivers a masterclass in slide guitar, soulful vocals, and timeless American music. First come, first served seating.',                                                                           NULL),
                                                                                                                ('2026-06-28 21:30:00', 'Kingfish Roots: One Love Night',           13, 'Sixth Street Social transforms into a reggae paradise as Kingfish Roots headlines One Love Night, a late-night celebration of roots reggae, conscious lyrics, and unstoppable rhythms. Food trucks and craft vendors on site.',                                                               20.00),
                                                                                                                ('2026-07-01 19:00:00', 'Georgia Gold: Southern Soul Revue',        14, 'The Peach Pit presents the Georgia Gold Southern Soul Revue, a spectacular evening of soul, gospel, and funk featuring the full 12-piece Georgia Gold band. This is a night of music that will stay with you long after the last note fades.',                                                35.00),
                                                                                                                ('2026-07-04 20:00:00', 'Static Revolt: Independence Bash',         15, 'Harbor Lights Hall hosts Static Revolt for a Fourth of July punk blowout. Static Revolt will tear through their entire back catalog plus a surprise set of cover songs. All ages welcome — free entry all night.',                                                                             NULL),
                                                                                                                ('2026-07-06 18:00:00', 'Los Fuegos: Fuego Fest',                   16, 'Desert Sun Arena ignites with Fuego Fest, a massive Latin fusion celebration headlined by Los Fuegos. Featuring special guest performers, a full dance floor, and an evening of flamenco, cumbia, and salsa that will have the whole arena on its feet.',                                    28.00),
                                                                                                                ('2026-07-10 19:30:00', 'The Revival Choir: Songs of the Spirit',  17, 'The Carolina Room welcomes The Revival Choir for Songs of the Spirit, an uplifting evening of gospel and inspirational music. Featuring a 20-voice ensemble and full live band, this transcendent performance is open to all.',                                                               10.00),
                                                                                                                ('2026-07-12 21:00:00', 'Sunken Groove: Funk All Night',            18, 'Tropicana Sound Club becomes the ultimate funk destination as Sunken Groove headlines Funk All Night, a non-stop dance party stretching past midnight. Expect deep bass lines, blazing brass, and a Miami crowd that knows how to move.',                                                    55.00),
                                                                                                                ('2026-07-15 17:30:00', 'The Midnight Clause: Unplugged',           1,  'In a rare acoustic performance, The Midnight Clause strips back their sound for an intimate unplugged session at The Iron Horse. Limited to 100 guests, this evening offers an up-close look at the quartet''s extraordinary musicianship.',                                                  NULL),
                                                                                                                ('2026-07-18 20:00:00', 'Dusty Horizon & Velvet Static: Together', 2,  'Two of the Midwest''s finest acts share the stage at The Rave for a special co-headlining night. Dusty Horizon opens with a full country set before Velvet Static closes the evening with their signature neo-soul fire.',                                                                    40.00),
                                                                                                                ('2026-07-20 18:30:00', 'Crown the Empire: Block Party Edition',   3,  'Crown the Empire brings the block party energy to Metro Chicago for a high-energy hip-hop showcase featuring local opening acts, freestyle cyphers, and the full Crown the Empire live experience.',                                                                                           15.00),
                                                                                                                ('2026-07-25 19:00:00', 'Circuit Breaker: Open Air Sessions',       4,  'Circuit Breaker returns to The Rusty Nail for a rare open-air electronic set. With a specially constructed outdoor stage and a custom lighting rig, this free evening promises to be one of the most visually stunning shows of the summer.',                                                 NULL),
                                                                                                                ('2026-07-30 21:30:00', 'Iron Parish & Mudwater Revival: Clash Night',5,'In the most unlikely pairing of the summer, metal titans Iron Parish and blues legends Mudwater Revival share the Northstar Amphitheater stage for an epic Clash Night. Each band performs a full headlining set, with a surprise collaborative finale to close out the evening.',           25.00);

-- -------------------------------------------------------
-- EVENT_PERFORMER
-- -------------------------------------------------------
INSERT INTO `event_performer` (`event_id`, `performer_id`) VALUES
                                                               (1,  1), (1,  2), (1,  3),
                                                               (2,  1), (2,  2),
                                                               (3,  2), (3,  3),
                                                               (4,  4), (4,  5),
                                                               (5,  6), (5,  7),
                                                               (6,  4), (6,  8),
                                                               (7,  9), (7,  10),
                                                               (8,  5), (8,  11),
                                                               (9,  12),(9,  13),
                                                               (10, 6), (10, 14),
                                                               (11, 7), (11, 15),
                                                               (12, 8), (12, 16),
                                                               (13, 9), (13, 17),
                                                               (14, 10),(14, 18),
                                                               (15, 11),(15, 12),
                                                               (16, 13),(16, 14),
                                                               (17, 15),(17, 16),
                                                               (18, 17),(18, 18),
                                                               (19, 4),
                                                               (20, 5), (20, 7),
                                                               (21, 6),
                                                               (22, 8),
                                                               (23, 10),(23, 12);

-- -------------------------------------------------------
-- EVENT_INTEREST
-- -------------------------------------------------------
INSERT INTO `event_interest` (`event_id`, `user_id`) VALUES
                                                         (1,  1),
                                                         (2,  2), (2,  3),
                                                         (3,  1), (3,  2),
                                                         (4,  2), (4,  5),
                                                         (5,  1), (5,  6),
                                                         (6,  3), (6,  7),
                                                         (7,  4), (7,  8),
                                                         (8,  5), (8,  9),
                                                         (9,  6), (9,  10),
                                                         (10, 7), (10, 11),
                                                         (11, 8), (11, 12),
                                                         (12, 9), (12, 13),
                                                         (13, 10),(13, 14),
                                                         (14, 11),(14, 15),
                                                         (15, 12),(15, 16),
                                                         (16, 13),(16, 17),
                                                         (17, 14),(17, 18),
                                                         (18, 15),(18, 1),
                                                         (19, 2), (19, 4),
                                                         (20, 3), (20, 5),
                                                         (21, 6), (21, 7),
                                                         (22, 8), (22, 9),
                                                         (23, 10),(23, 11);

-- -------------------------------------------------------
-- PERFORMER_FOLLOW
-- -------------------------------------------------------
INSERT INTO `performer_follow` (`performer_id`, `user_id`) VALUES
                                                               (1,  1), (1,  2), (1,  3),
                                                               (2,  1), (2,  2),
                                                               (3,  1), (3,  2), (3,  3),
                                                               (4,  1), (4,  2),
                                                               (5,  3), (5,  4),
                                                               (6,  5), (6,  6),
                                                               (7,  7), (7,  8),
                                                               (8,  1), (8,  9),
                                                               (9,  10),(9,  2),
                                                               (10, 11),(10, 3),
                                                               (11, 12),(11, 4),
                                                               (12, 13),(12, 5),
                                                               (13, 14),(13, 6),
                                                               (14, 15),(14, 7),
                                                               (15, 16),(15, 8),
                                                               (16, 17),(16, 9),
                                                               (17, 18),(17, 10),
                                                               (18, 1), (18, 11);

-- -------------------------------------------------------
-- VENUE_FOLLOW
-- -------------------------------------------------------
INSERT INTO `venue_follow` (`user_id`, `venue_id`) VALUES
                                                       (1,  1), (2,  1), (3,  1),
                                                       (1,  2), (2,  2),
                                                       (1,  3),
                                                       (4,  1), (4,  2),
                                                       (5,  3), (5,  4),
                                                       (6,  5), (6,  6),
                                                       (7,  7), (7,  8),
                                                       (8,  9), (8,  10),
                                                       (9,  11),(9,  12),
                                                       (10, 13),(10, 14),
                                                       (11, 15),(11, 16),
                                                       (12, 17),(12, 18),
                                                       (13, 1), (13, 2),
                                                       (14, 3), (14, 4),
                                                       (15, 5), (15, 6),
                                                       (16, 7);

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;